function [image,GMatrix] = SubPlot3 (image,GMatrix,FString)
 % Create the figure window with the specified properties
  fig = figure('Name','ImageProcessing','Color',[1 1 1],'Position',[250,90,800,500],'MenuBar','none','NumberTitle','off');
  labelMessage="plotting "+FString+" Algorithim";
  % Create the label
  label = uicontrol(fig,'style','text','string',labelMessage,'Position',[170,450,500,40],'BackgroundColor',[1 1 1],'Fontweight','bold','Fontsize',12,'ForegroundColor', [0.23 0.60 0.73],'FontName','Wide Latin');
  TextField1 = uicontrol(fig,'style','edit','enable','on','Position',[540,400,250,30],'Tag','txt'); 
  Submit1 = uicontrol(fig, 'Style', 'pushbutton', 'String', 'SubmitImage','Position',[690,360,100,30],'BackgroundColor', [0.23 0.60 0.73], ...
                        'ForegroundColor', [1 0.95 0.86], ...
                        'FontSize', 12,...
                        'FontName', 'Times New Roman',...
                        'HorizontalAlignment', 'center', ...
                        'Callback', @SubmitImage);
  Submit2 = uicontrol(fig, 'Style', 'pushbutton', 'String', 'SubmitInput','Position',[540,360,100,30],'BackgroundColor', [0.23 0.60 0.73], ...
                        'ForegroundColor', [1 0.95 0.86], ...
                        'FontSize', 12,...
                        'FontName', 'Times New Roman',...
                        'HorizontalAlignment', 'center', ...
                        'Callback', @SubmitInput);
  Submit3 = uicontrol(fig, 'Style', 'pushbutton', 'String', 'Submit','Position',[690,320,100,30],'BackgroundColor', [0.23 0.60 0.73], ...
                        'ForegroundColor', [1 0.95 0.86], ...
                        'FontSize', 12,...
                        'FontName', 'Times New Roman',...
                        'HorizontalAlignment', 'center', ...
                        'Callback', @Apply);
  Backk = uicontrol(fig, 'Style', 'pushbutton', 'String', 'Back','Position',[540,280,100,30],'BackgroundColor', [0.23 0.60 0.73], ...
                        'ForegroundColor', [1 0.95 0.86], ...
                        'FontSize', 12,...
                        'FontName', 'Times New Roman',...
                        'HorizontalAlignment', 'center', ...
                        'Callback', @Back);
  Histogramm1 = uicontrol(fig, 'Style', 'pushbutton', 'String', 'Histogram','Position',[540,320,100,30],'BackgroundColor', [0.23 0.60 0.73], ...
                        'ForegroundColor', [1 0.95 0.86], ...
                        'FontSize', 12,...
                        'FontName', 'Times New Roman',...
                        'HorizontalAlignment', 'center', ...
                         'Callback', @Histo);
  Savee = uicontrol(fig, 'Style', 'pushbutton', 'String', 'Save','Position',[613,240,100,30],'BackgroundColor', [0.23 0.60 0.73], ...
                        'ForegroundColor', [1 0.95 0.86], ...
                        'FontSize', 12,...
                        'FontName', 'Times New Roman',...
                        'HorizontalAlignment', 'center', ...
                         'Callback', @export);
  Reset1 = uicontrol(fig, 'Style', 'pushbutton', 'String', 'Reset','Position',[690,280,100,30],'BackgroundColor', [0.23 0.60 0.73], ...
                        'ForegroundColor', [1 0.95 0.86], ...
                        'FontSize', 12,...
                        'FontName', 'Times New Roman',...
                        'HorizontalAlignment', 'center', ...
                        'Callback', @Reset);
  display_path="";
  Original1 = axes(fig,'Position',[0.02 0.6 0.3 0.3],'visible','off','Tag','ax1');
  Original2= axes(fig,'Position',[0.35 0.6 0.3 0.3],'visible','off','Tag','ax1');
  Enhanced= axes(fig,'Position',[0.25 0.2 0.3 0.3],'visible','off','Tag','ax1');
  Histog = axes(fig,'Position',[0.68 0.04 0.3 0.4],'visible','off','Tag','ax1');
  function SubmitImage(hObject,eventdata)
        [filename,pathname]=uigetfile('*','select your ecg signal');
        display_path = strcat(pathname,filename);
        TextField1.String=display_path;
        message=sprintf('Your image is added succefully !');
        uiwait(msgbox(message));
  end
  
 function Back(hObject,eventdata)
      Spatial(image,GMatrix);
      close(fig);
 end


 function Apply(hObject,eventdata)
    switch FString
     case "Subtract 2 images"
        Submitted=imread(display_path);
        output=SubtractTwoImages(GMatrix,Submitted);
        GMatrix=output;
        imshow(image,'Parent',Original1);
        imshow(Submitted,'Parent',Original2);
        imshow(GMatrix,'Parent',Enhanced);
    
    case "Add two"
       Submitted=imread(display_path);
       output=AddingTwoImages(GMatrix,Submitted);
       GMatrix=output;
       imshow(image,'Parent',Original1);
       imshow(Submitted,'Parent',Original2);
       imshow(GMatrix,'Parent',Enhanced);
    end
 end

function Histo(hObject,eventdata)
      counts=Histogram(GMatrix);
      grayLevels = 0 : 255;
      bar(Histog ,grayLevels, counts, 'BarWidth', 5, 'FaceColor', 'b');
      xlabel('Gray Level', 'FontSize', 10);
      ylabel('Pixel Count', 'FontSize', 10);
      grid on;
 end
 function export(hObject,eventdata)
         [file, path] = uiputfile('*.jpg', 'Save processed image as *.jpg');
        imwrite(GMatrix, fullfile(path, file));
 end

 function Reset(hObject,eventdata)
    GMatrix=image;
    message = sprintf("Your image is resetted to the original image succefully ! ");
    uiwait(msgbox(message));
 end

  
end